version: "3.8"

services:
  nginx-reverse-proxy:
    image: nginx:latest
    container_name: "nginx-reverse-proxy"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-network

networks:
  my-network:
    external: true